import { app, ipcMain, Menu, Tray } from "electron";
import unhandled from "electron-unhandled";
import { menubar as Menubar } from "menubar";
import NodeMediaServer from "node-media-server";
import updateElectronApp from "update-electron-app";

unhandled();

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  // eslint-disable-line global-require
  app.quit();
}

const isFirstInstance = app.requestSingleInstanceLock();

if (!isFirstInstance) {
  app.quit();
}

updateElectronApp();

app.whenReady().then(() => {
  app.setLoginItemSettings({
    openAtLogin: true,
    openAsHidden: true,
  });
  const trayIconPath = __dirname + "/assets/img/IconTemplate.png";
  const tray = new Tray(trayIconPath);
  const menu = Menu.buildFromTemplate([
    { label: "Quit", click: () => app.quit() },
  ]);
  tray.on("right-click", () => {
    tray.popUpContextMenu(menu);
  });
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const menubar = Menubar({
    tray,
    index: MAIN_WINDOW_WEBPACK_ENTRY,
    preloadWindow: true,
    showDockIcon: false,
    browserWindow: {
      webPreferences: {
        nodeIntegration: true,
        contextIsolation: false,
        enableRemoteModule: true,
      },
    },
  });
  menubar.on("ready", async () => {
    if (!app.getLoginItemSettings().wasOpenedAsHidden) {
      menubar.showWindow();
    }
  });
  app.on("second-instance", () => {
    menubar.showWindow();
  });
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

ipcMain.on("getVersion", (ev) => {
  ev.reply("getVersion-reply", app.getVersion());
});

const nms = new NodeMediaServer({
  rtmp: {
    port: 1935,
    chunk_size: 60000,
    gop_cache: true,
    ping: 30,
    ping_timeout: 60,
  },
});

nms.run();

nms.on("preConnect", (id, args) => {
  console.log(
    "[NodeEvent on preConnect]",
    `id=${id} args=${JSON.stringify(args)}`
  );
});

nms.on("postConnect", (id, args) => {
  console.log(
    "[NodeEvent on postConnect]",
    `id=${id} args=${JSON.stringify(args)}`
  );
});

nms.on("doneConnect", (id, args) => {
  console.log(
    "[NodeEvent on doneConnect]",
    `id=${id} args=${JSON.stringify(args)}`
  );
});

nms.on("prePublish", (id, streamPath, args) => {
  console.log(
    "[NodeEvent on prePublish]",
    `id=${id} StreamPath=${streamPath} args=${JSON.stringify(args)}`
  );
  // if (args.key !== "mysecretstreamkey") {
  //   const session = nms.getSession(id);
  //   session.reject();
  // }
});

nms.on("postPublish", (id, streamPath, args) => {
  console.log(
    "[NodeEvent on postPublish]",
    `id=${id} StreamPath=${streamPath} args=${JSON.stringify(args)}`
  );
});

nms.on("donePublish", (id, streamPath, args) => {
  console.log(
    "[NodeEvent on donePublish]",
    `id=${id} StreamPath=${streamPath} args=${JSON.stringify(args)}`
  );
});
