name: Build
on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.builds.runsOn }}
    strategy:
      matrix:
        builds: 
          - os: windows-latest
            runsOn: [windows, self-hosted]
          - os: macOS-latest
            runsOn: [macOS-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@master
        with:
          node-version: 14

      - name: decode windows cert
        run: ./scripts/decode-windows-cert.sh
        env:
          WINDOWS_CERT_P12: ${{ secrets.WINDOWS_CERT_P12 }}
        if: matrix.builds.os == 'windows-latest'
        shell: bash

      - name: decode macos cert
        run: ./scripts/decode-macos-cert.sh
        env:
          MACOS_CERT_P12: ${{ secrets.MACOS_CERT_P12 }}
        if: matrix.builds.os == 'macOS-latest'

      - name: install dependencies
        run: yarn install
        env:
          FONTAWESOME_NPM_TOKEN: ${{ secrets.FONTAWESOME_NPM_TOKEN }}

      - name: build
        run: yarn make
        env:
          APP_STORE_CONNECT_ID: ${{ secrets.APP_STORE_CONNECT_ID }}
          APP_STORE_CONNECT_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
          WINDOWS_CERT_PASSWORD: ${{ secrets.WINDOWS_CERT_PASSWORD }}
          FONTAWESOME_NPM_TOKEN: ${{ secrets.FONTAWESOME_NPM_TOKEN }}
