name: Publish
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macOS
            runs-on: [macOS-latest]
          - os: windows
            runs-on: [windows, self-hosted]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@master
        with:
          node-version: 14

      - name: decode windows cert
        run: ./scripts/decode-windows-cert.sh
        env:
          WINDOWS_CERT_P12: ${{ secrets.WINDOWS_CERT_P12 }}
        if: matrix.os == 'windows'
        shell: bash

      - name: decode macos cert
        run: ./scripts/decode-macos-cert.sh
        env:
          MACOS_CERT_P12: ${{ secrets.MACOS_CERT_P12 }}
        if: matrix.os == 'macOS'

      - name: install dependencies
        run: yarn install
        env:
          FONTAWESOME_NPM_TOKEN: ${{ secrets.FONTAWESOME_NPM_TOKEN }}

      - name: publish
        run: yarn run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_STORE_CONNECT_ID: ${{ secrets.APP_STORE_CONNECT_ID }}
          APP_STORE_CONNECT_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
          WINDOWS_CERT_CONTAINER_NAME: ${{ secrets.WINDOWS_CERT_CONTAINER_NAME }}
          FONTAWESOME_NPM_TOKEN: ${{ secrets.FONTAWESOME_NPM_TOKEN }}
